### ISSUE TITLE
When viewing text, paragraphs are ignored 

### ISSUE THREAD

**Issue by albertocottica** [opencarecc/graph-ryder-dashboard#5]
![image](https://cloud.githubusercontent.com/assets/1976806/23138158/00a3bfca-f7a6-11e6-9189-4f15c8568d98.png)

**Comment by jason-vallet** [comment]
When getting the json logs from ER, the web encoding is scrapped, leaving us with plain text.
This is usually a good practice to avoid code injection (html, php, js) but sadly results in unformatted text.

Aside from this, the default json parser is kinda touchy about return and other special characters (\n, \t) and I have been forced to ignore those when reading the json to avoid errors.

However, speaking about it made me think of a way to maybe correct this behaviour. I will look into it.

**Comment by jason-vallet** [comment]
Ok, it was not so hard after all, I just had to tweak a thing or two in the Drupal views to get the html code directly.
So we now can see the paragraphs but also the formatting used on Drupal and even the pictures.
It makes the read significantly easier and more enjoyable to say the least!

I will push the commit during the week-end as the database needs to be flushed to replace the current content with the raw html code.
 
Small preview:
![screenshot from 2017-02-24 18 58 33](https://cloud.githubusercontent.com/assets/2879855/23314701/5e563146-fac3-11e6-8c45-cc26908054e8.png)

**Comment by guywiz** [comment]
Well done Jason!

**Comment by albertocottica** [comment]
Excellent. 

Drupal Views does have the capability of returning the HTML, but how much more fragile does this new change make the code? Can we get gigantic pop-ups when pictures are large? Or any other mess? Readability is important, but so is reliability. We intend to use this for some time, when Jason is not around to fix bugs for us!

**Comment by jason-vallet** [comment]
I have used an instruction specific to Angular which should make the code reliably safe*ish* (if there is such thing) and resistant to injection.

The panel size is another story which need to be address indeed. For now, I have stick with the rule of displaying panels with the same initial size: 30% of the navigator size. This choice was completely arbitrary but looked alright at the time and can be modified. However, legibility problems arise if you wish to make the website mobile compliant (I don't recall this point being discussed previously) or if the browser window is too small.
On standard computers, the problem is not really present as, following Noemi's request, the windows can be resized by hand (well by mouse more precisely). On this, some work is still needed on the css style to make the whole thing without glitches (mostly by fixing the minimum sizes to avoid over-shrinking).

**Comment by guywiz** [comment]
Not sure my comment on GitHub went through (the issue was closed).

I was saying: good job, Jason!

I went to see this new version, the well formatted content is much more user-friendly. It seems however there is a problem recovering comments (subject systematically are entitle « Nan »), bios of users are empty. Might be a db reconstruction problem?

Guy
—

**Comment by jason-vallet** [comment]
Your message was send but I can reopen the issue as we keep the discussion going. 

The fact that you have a biography tab indicates that something is not up to date. Are you using your local installation or the distant one ? If it is a local deployment, you need to update your code using the github version available on my personal repo (for both the api and the dashboard). If your use the ovh server, try to update a few times the page or clear your browser cache.

The Nan subjects should fix themselves at the same time I believe. I tried the website on Chrome (well Chromium) and Firefox and everything seemed to work fine. Are you using Safari or another browser I should try? 

PS: just to be safe, you should hide/delete your private signature when posting on public forums. Just sayin'...

**Comment by albertocottica** [comment]
Closing.
